name: Docker image build + Docker Hub + Azure Kubernetes Service + Variables + Secrets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
        
    env:      
      PROJECT_PATH: ./APICount
      AZURE_RESOURCE_GROUP_K8S: TestKubernetes
      AZURE_CLUSTER_K8S: AKSCluster
      NAMESPACE_K8S: tech-meetup
      DEPLOYMENT_K8S: apicountk8s

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login - Docker Hub
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push in Docker Hub
      run: |
        cd ${{ env.PROJECT_PATH }}
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}
